version: 0.0
os: linux
files:
  - source: Config/config.txt
    destination: /Users/royyuan/Desktop/script_stuff
  - source: source
    destination: /Users/royyuan/Desktop/script_stuff
hooks:
  BeforeInstall:
    - location: /Users/royyuan/Desktop/script_stuff
    - location: /Users/royyuan/Desktop/script_stuff
  AfterInstall:
    - location: /Users/royyuan/Desktop/script_stuff
      timeout: 180
  ApplicationStart:
    - location: /Users/royyuan/Desktop/script_stuff
      timeout: 3600
  ValidateService:
    - location: /Users/royyuan/Desktop/script_stuff
      timeout: 3600
      runas: codedeployuser
